### ISSUE TITLE
Missing License

### ISSUE THREAD

**Issue by justinba1010** [liubko/bs-react-select#4]
Hey we noticed that there's a reference to an MIT license in the `packages.json`, is that the correct license? If so would you guys mind if I put up a PR containing the license? We really like the project bridging the gap for ReasonReact Select!

Thank you

**Comment by liubko** [comment]
@justinba1010 thanks for bringing up the issue, resolved it here https://github.com/ahrefs/bs-react-select/commit/feda4ffbcd5c7d35e6905100e5497e6446e01596 and sorry for such a delay

**Comment by liubko** [comment]
_and sorry for such a delay_
